### ISSUE TITLE
Cannot understand rgb2yuv function code 

### ISSUE THREAD

**Issue by wan-h** [TachibanaYoshino/AnimeGANv2#14]
```
def rgb2yuv(rgb):
    """
    Convert RGB image into YUV https://en.wikipedia.org/wiki/YUV
    """
    rgb = (rgb + 1.0)/2.0
    return tf.image.rgb_to_yuv(rgb)
```
tf.image.rgb_to_yuv(rgb) do the op: rgb_to_yuv
so,I can't understand what this line of code means： "rgb = (rgb + 1.0)/2.0"

**Comment by TachibanaYoshino** [comment]
To calculate yuv, it is necessary to limit the input value range in advance。
