### ISSUE TITLE
sample models coming soon?

### ISSUE THREAD

**Issue by tripzero** [TachibanaYoshino/AnimeGANv2#2]

**Comment by TachibanaYoshino** [comment]
I don't quite understand what you mean.

**Comment by tripzero** [comment]
I mean the model checkpoint link.  In the README it says TBD.  I'm just
wondering when it will be determined. :)

**Comment by TachibanaYoshino** [comment]
The model checkpoints is in the checkpoint directory, and Shinkai's model is still being debugged. The TBD item refers to the dataset download link.
