### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by AlexRMU** [TachibanaYoshino/AnimeGANv2#3]
Add a colab, please

**Comment by TachibanaYoshino** [comment]
Sorry, due to network restrictions, I cannot do that right now.

**Comment by AlexRMU** [comment]
For example
[anime.ipynb.txt](https://github.com/TachibanaYoshino/AnimeGANv2/files/5058260/anime.ipynb.txt)

**Comment by AlexRMU** [comment]
Delete in the name .txt

**Comment by JanGross** [comment]
I'm working on an extended notebook for photos and videos right now. Will share once it's working properly

**Comment by JanGross** [comment]
Here's the Colab notebook: https://colab.research.google.com/drive/1kfDP4vj0E7REoUZjXqGTk3MP-atJq3cO
Also see #4 
This was the first time I worked with a Colab notebook, so there's probably room for improvement.
