### ISSUE TITLE
Can I train a model by using multiple GPUs?

### ISSUE THREAD

**Issue by MorningStarJ** [TachibanaYoshino/AnimeGANv2#33]
Thank you for your awesome project. 
I think if i can using mulitple GPUs to traning, it's making things be more efficient. Hope to get some advice from you. Thanks.

**Comment by TachibanaYoshino** [comment]
Sorry for the late reply, you can implement training using multiple GPUs yourself. Due to the lack of hardware resources, I have no conditions to use more GPUs.

**Comment by MorningStarJ** [comment]
> Sorry for the late reply, you can implement training using multiple GPUs yourself. Due to the lack of hardware resources, I have no conditions to use more GPUs.

Thank you for your response.

**Comment by TachibanaYoshino** [comment]
Sorry for the late reply, you can implement training using multiple GPUs yourself. Due to the lack of hardware resources, I have no conditions to use more GPUs.
